### PR TITLE
Fix relative path usage bug

### LINKED ISSUE #14: XCreateFile fail to open config.txt
For some unknown reason XCreateFile (inside load_conf_file function) is unable to open the config.txt.

I remember this working the last time I checked (first days of Jan). I'll give it a look soon.

### PR DESCRIPTION
**Pull request by ergo720**
This is intended to fix the relative path bug issue introduced in https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/pull/61. I already tested this on both my Xbox and with https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/08691c24e17f48e7cecc839fb4a7fd6543d332c5 and I can confirm that they are both able to open `config.txt` and write `kernel_tests.log` files.

Closes https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/issues/14

### CODE REVIEW

File: output.c [hunk 1]
```diff
@@ -49,15 +49,15 @@ void print_test_footer(
     }
 }
 
-void open_output_file(char* file_name) {
+void open_output_file(char* output_file_path) {
```
Comment (RadWolfie) [inline output.c]: Include `output_` to the argument isn't needed when the function name is `open_output_file`. Plus there's only one file path input to the function. However, `file_path` is better than `file_name`.

**Comment by JayFoxRox** [comment]
~~This PR should probably be marked for closing #14? (the previous PR #61 aimed to do it, but actually didn't?)~~ *This was added to the PR description.*

File: output.c (hunk 1 above)
Comment (ergo720) [reply output.c]: I changed `output_file_path` to `file_path` and also `config_file_path` to `file_path` in `load_conf_file` or else the name of the argument of the two functions would become inconsistent (which is also why I did this change in the first place).

**Review by RadWolfie — APPROVED** [review]
